export const FAQ_SECTIONS = [
  {
    "category": "PROCESS",
    "items": [
      {
        "question": "How does beMore's design process work?",
        "answer": "Every project at beMore follows a clear four-stage process designed to eliminate guesswork and keep things moving smoothly.\n\n**Stage 1 \u2014 Discover (Week 1\u20132)**\nWe begin with a detailed conversation at your site. This isn't a sales pitch \u2014 it's a listening session. We walk through your space, understand how your family lives and works, discuss what's bothering you about the current layout, and talk through your budget honestly. We also take measurements, photograph the space, and note structural constraints like beams, columns, plumbing risers, and electrical panels. By the end of this stage, we have a clear project brief that both sides agree on.\n\n**Stage 2 \u2014 Design (Week 2\u20134)**\nThis is where the ideas take shape. We create detailed floor plans, 3D walkthroughs, and material mood boards so you can experience your space before anything is built. You'll see exactly how your kitchen, wardrobes, lighting, and furniture will look and feel. We typically present two to three design directions and refine based on your feedback. Nothing moves forward until you're fully comfortable with the design.\n\n**Stage 3 \u2014 Detail (Week 4\u20135)**\nOnce the design is approved, we prepare working drawings for every element \u2014 carpentry details, electrical layouts, plumbing points, false ceiling plans, tile layouts, and paint specifications. We also finalize the Bill of Quantities (BOQ) so you know the exact cost of every item before execution begins. This stage is about precision \u2014 no surprises later.\n\n**Stage 4 \u2014 Deliver (Week 5\u20138+)**\nExecution begins on site. Our project manager oversees every trade \u2014 civil, carpentry, electrical, plumbing, painting, and installation \u2014 with regular site visits and progress updates shared with you. We conduct quality checks at each milestone and do a final walkthrough together before handover. The timeline for execution varies based on the scope, but most apartment interiors are completed within 45\u201360 days from the start of site work."
      },
      {
        "question": "How long does a typical interior design project take in Bangalore?",
        "answer": "For a standard apartment interior (2BHK or 3BHK), the total timeline from first meeting to move-in is typically **8 to 12 weeks**. This breaks down roughly as follows: 2 weeks for design and planning, 1 week for detailed drawings and BOQ finalization, and 5 to 8 weeks for on-site execution.\n\nHere's what affects the timeline:\n\n- **Scope of work:** A full-home interior with civil modifications, modular kitchen, wardrobes, false ceiling, electrical rewiring, and painting takes longer than a partial scope covering just a kitchen and bedrooms.\n- **Civil work:** If your project involves breaking walls, bathroom waterproofing, or structural changes, add 1\u20132 weeks for civil work before carpentry can begin.\n- **Material lead times:** Custom-made furniture, imported tiles, or specialty hardware may have 2\u20133 week lead times. We plan procurement early to avoid delays.\n- **Approvals and decisions:** The faster you finalize design choices and material selections, the faster we can move. Most delays happen when decisions are pending from the homeowner's side.\n\nFor independent houses and villas, expect 3 to 6 months depending on the scale. Commercial and hospitality projects vary widely \u2014 a small caf\u00e9 might take 6\u20138 weeks, while a large office fit-out could take 3\u20134 months.\n\nWe provide a detailed project timeline at the start of every engagement so both sides know exactly what to expect and when."
      },
      {
        "question": "What happens during the first consultation?",
        "answer": "The first consultation is a free, no-obligation conversation \u2014 either at your site or at our studio in Basaveshwar Nagar, Bangalore. It typically lasts 45 minutes to an hour.\n\nHere's what we cover:\n\n- **Understanding your needs:** We ask about your family, lifestyle, how you use each room, what you love about your current space, and what frustrates you. If it's a new apartment, we talk about what you want your home to feel like.\n- **Budget discussion:** We talk numbers openly. Knowing your budget range early helps us design within realistic boundaries rather than presenting ideas you can't execute.\n- **Site assessment:** If we meet at your home, we do a preliminary walkthrough \u2014 noting the apartment layout, natural light, ventilation, existing fixtures, and any structural elements that will affect the design.\n- **Process and timeline overview:** We explain how our process works, what deliverables you'll receive, and a rough timeline for your specific project.\n- **Next steps:** If there's a mutual fit, we share a design proposal within a few days outlining the scope, fees, and timeline.\n\nThere's absolutely no pressure to commit during the first meeting. It's an honest conversation to see if we're the right studio for your project."
      },
      {
        "question": "Do you provide 3D walkthroughs before execution?",
        "answer": "Yes, every project includes detailed 3D visualizations and walkthroughs as a standard part of our design process \u2014 not as an add-on or premium feature.\n\nBefore a single wall is touched or a single material is ordered, you'll see:\n\n- **Photorealistic 3D renders** of every room showing furniture placement, material finishes, lighting, and colours exactly as they will appear in reality.\n- **3D walkthrough videos** that let you virtually \"walk through\" your home, moving from room to room to understand spatial flow and proportions.\n- **Multiple angles and options** \u2014 we typically show you how a space looks in daylight and with evening lighting, and present two to three material palette options so you can compare.\n\nThis is one of the most important parts of our process. It ensures there are no surprises during execution. What you see in the 3D render is what gets built on site. If something doesn't feel right in the visualization, we change it on screen \u2014 which costs nothing \u2014 rather than discovering the problem after it's been built."
      },
      {
        "question": "Can I make changes after the design is finalized?",
        "answer": "Yes, but with a few practical considerations.\n\n**During the design phase** (before execution begins), changes are easy and free. That's precisely why we invest so much time in 3D walkthroughs and detailed planning \u2014 so you can see, adjust, and finalize everything on screen where changes cost nothing.\n\n**Once execution has started**, changes become more complex:\n\n- **Minor changes** like swapping a paint colour, changing handle hardware, or adjusting shelf heights can usually be accommodated without major impact on timeline or cost.\n- **Major changes** \u2014 like altering the kitchen layout after cabinets have been measured and ordered, or moving plumbing points after tiling is done \u2014 will affect both the budget and the timeline. We'll always give you an honest assessment of the cost and delay before proceeding, so you can make an informed decision.\n\nOur advice: take the design phase seriously. Spend the time with the 3D renders. Show them to your family. Sleep on it. The more confident you are before we start on site, the smoother and more cost-effective the execution will be."
      },
      {
        "question": "Do you handle civil and structural modifications?",
        "answer": "Yes, we handle civil work as part of our end-to-end service. This includes:\n\n- **Wall demolition and construction** \u2014 removing walls to create open-plan layouts, building new partition walls, or creating utility rooms and storage nooks.\n- **Bathroom renovations** \u2014 breaking existing tiles, re-waterproofing, re-plumbing, and re-tiling bathrooms from scratch.\n- **Kitchen modifications** \u2014 relocating plumbing points, extending countertops into adjacent spaces, creating breakfast counters, or converting closed kitchens to semi-open layouts.\n- **Flooring work** \u2014 removing old flooring and laying new tiles, marble, or wood flooring.\n- **Structural assessments** \u2014 for load-bearing wall modifications, we work with licensed structural engineers to ensure safety and compliance.\n\nFor apartment projects, we also handle the necessary approvals from your apartment association or builder for any structural changes. We know the common rules and restrictions in most major Bangalore apartment complexes.\n\nOne important note: if your apartment is in a building that's less than a few years old, some structural modifications may void the builder's warranty. We always flag this upfront so you can make an informed choice."
      },
      {
        "question": "What is your 60-day delivery commitment?",
        "answer": "Our 60-day benchmark refers to the on-site execution timeline for a standard full-home apartment interior (2BHK or 3BHK) after the design is finalized and all materials and finishes have been approved.\n\nHere's what makes this possible:\n\n- **Front-loaded planning:** By the time we begin on site, every detail \u2014 from the exact tile layout to the number of electrical points \u2014 has been finalized in the design phase. This eliminates decision-making delays during execution.\n- **Parallel workstreams:** We schedule civil work, carpentry, electrical, and plumbing to overlap where possible rather than running sequentially. For example, while the kitchen cabinets are being manufactured in the workshop, civil modifications and electrical work happen simultaneously on site.\n- **Procurement planning:** We order materials and fixtures at the start of the project so that nothing is waiting on delivery during execution.\n\nA few things that can extend the 60-day timeline: extensive civil or structural work, custom imported materials with long lead times, or delays in homeowner approvals during execution. We communicate proactively if anything affects the schedule.\n\nFor larger projects like villas, independent houses, or commercial spaces, the timeline is estimated on a case-by-case basis and shared upfront in the project proposal."
      }
    ]
  },
  {
    "category": "COST",
    "items": [
      {
        "question": "How much does interior design cost in Bangalore per square foot?",
        "answer": "Interior design cost in Bangalore typically ranges from **\u20b91,500 to \u20b93,500 per square foot** for complete interiors in 2026, depending on the scope of work, quality of materials, and level of customization.\n\nHere's a realistic breakdown:\n\n- **Essential interiors (\u20b91,200\u2013\u20b91,800 per sq ft):** Covers the basics \u2014 modular kitchen, wardrobes, basic false ceiling, standard laminate finishes, and functional lighting. Suitable for rental properties or budget-conscious homeowners who want clean, practical interiors.\n- **Mid-range interiors (\u20b91,800\u2013\u20b92,500 per sq ft):** The most popular range for Bangalore homeowners. Includes better quality laminates or veneers, designed false ceilings with cove lighting, customized storage solutions, good quality hardware (Hettich or Hafele), and considered lighting design.\n- **Premium interiors (\u20b92,500\u2013\u20b94,000+ per sq ft):** Custom furniture, premium veneers or PU/acrylic finishes, natural stone or imported tiles, designer lighting, smart home elements, and bespoke detailing throughout.\n\nThese per-square-foot figures typically include carpentry (kitchen, wardrobes, TV units, storage), false ceiling, basic electrical modifications, painting, and installation. They usually do **not** include major civil work, HVAC, full bathroom renovations, loose furniture (sofas, dining tables, beds), curtains, or appliances \u2014 these are quoted separately.\n\nAt beMore, we work primarily in the mid-range to premium segment (\u20b91,800\u2013\u20b93,500+ per sq ft) because our clients value design quality, material honesty, and lasting craftsmanship. We provide a detailed BOQ (Bill of Quantities) before execution so you know exactly what every rupee is being spent on."
      },
      {
        "question": "What is the cost of 2BHK interior design in Bangalore?",
        "answer": "A complete 2BHK interior in Bangalore (typically 800\u20131,100 sq ft) costs between **\u20b98 lakhs and \u20b918 lakhs** in 2026, depending on the scope and material quality.\n\nHere's a rough room-wise breakdown for a mid-range 2BHK project:\n\n- **Modular Kitchen:** \u20b92.5\u2013\u20b95 lakhs (L-shaped or U-shaped, with chimney, granite/quartz countertop, Hettich/Hafele hardware)\n- **Master Bedroom:** \u20b91.5\u2013\u20b93 lakhs (sliding wardrobe, bed back panel or headboard wall, side tables, dresser unit)\n- **Second Bedroom:** \u20b91\u2013\u20b92 lakhs (wardrobe, study unit, basic storage)\n- **Living & Dining:** \u20b91.5\u2013\u20b93 lakhs (TV unit, shoe rack, crockery unit, false ceiling, accent wall)\n- **False Ceiling & Lighting:** \u20b91\u2013\u20b92 lakhs (across the home)\n- **Painting:** \u20b90.5\u2013\u20b91 lakh (depends on type \u2014 emulsion, texture, or accent walls)\n- **Electrical Modifications:** \u20b90.3\u2013\u20b90.7 lakhs\n\nAt beMore, most of our 2BHK projects fall in the \u20b912\u2013\u20b918 lakh range because our clients typically want quality materials, thoughtful design, and finishes that last. We provide a detailed cost estimate before any work begins, and our payment structure is milestone-based so you're always in control."
      },
      {
        "question": "What is the cost of 3BHK interior design in Bangalore?",
        "answer": "A full 3BHK interior design in Bangalore (typically 1,200\u20131,800 sq ft) costs between **\u20b912 lakhs and \u20b930 lakhs** in 2026.\n\nHere's how the budget typically distributes across a mid-to-premium 3BHK:\n\n- **Modular Kitchen:** \u20b93\u2013\u20b96 lakhs \u2014 the kitchen usually takes 20\u201325% of the total budget, especially with premium hardware, a good chimney, and quality countertops.\n- **Master Bedroom with Wardrobe:** \u20b92\u2013\u20b94 lakhs\n- **Second Bedroom:** \u20b91.5\u2013\u20b93 lakhs\n- **Third Bedroom / Guest Room:** \u20b91\u2013\u20b92.5 lakhs\n- **Living, Dining & Foyer:** \u20b92\u2013\u20b94 lakhs\n- **False Ceiling & Lighting (full home):** \u20b91.5\u2013\u20b93 lakhs\n- **Painting (full home):** \u20b90.7\u2013\u20b91.5 lakhs\n- **Electrical & Plumbing Modifications:** \u20b90.5\u2013\u20b91 lakh\n- **Balcony / Utility Area:** \u20b90.3\u2013\u20b90.8 lakhs\n\nMost of our 3BHK clients in areas like Indiranagar, Koramangala, HSR Layout, and Whitefield invest between \u20b918\u2013\u20b928 lakhs for a complete interior that balances quality with value.\n\nA word of caution: be wary of quotes that seem significantly below the market range. Low quotes often exclude items like false ceiling, painting, electrical work, or hardware \u2014 which get added later as \"extras.\" We include everything in our BOQ upfront so the number you approve is the number you pay."
      },
      {
        "question": "What is the cost of villa interior design in Bangalore?",
        "answer": "Villa interiors in Bangalore typically range from **\u20b91,800 to \u20b93,500+ per square foot**, with total project costs usually falling between **\u20b925 lakhs and \u20b91 crore+** depending on the size and level of customization.\n\nVillas differ from apartment interiors in several ways that affect cost:\n\n- **Larger scale:** Villas typically range from 2,500 to 5,000+ sq ft, which means more rooms, more wardrobes, more bathrooms, and more furniture.\n- **Architectural integration:** Unlike apartments where the structure is fixed, villas often involve architectural modifications \u2014 staircase redesigns, terrace enclosures, courtyard treatments, landscape integration, and sometimes structural additions.\n- **Premium expectations:** Villa clients generally expect higher-end finishes \u2014 solid wood or premium veneer wardrobes, natural stone flooring, designer bathroom fittings, custom lighting schemes, and bespoke furniture pieces.\n- **Outdoor spaces:** Terraces, gardens, sit-outs, and sometimes swimming pool areas need design attention that apartments don't require.\n- **Multiple bathrooms:** A 4BHK villa might have 4\u20135 bathrooms, and bathroom renovations with good fittings can cost \u20b91.5\u2013\u20b93 lakhs each.\n\nAt beMore, our villa projects in areas like Whitefield, JP Nagar, Hebbal, and North Bangalore typically fall in the \u20b940 lakh\u2013\u20b980 lakh range for comprehensive interiors. For full architectural + interior projects starting from bare structure, the investment can be higher.\n\nWe always begin with a detailed scope discussion and provide a transparent BOQ so you can prioritize what matters most and phase the work if needed."
      },
      {
        "question": "Do you charge a design consultation fee?",
        "answer": "**The first consultation is free.** This is a 45-minute to one-hour conversation either at your site or at our studio where we understand your project, discuss your needs and budget, and explain our process. There's no obligation.\n\nIf you choose to move forward with us, the design phase is a paid engagement. Here's how our fee structure works:\n\n- **Design fee:** This covers space planning, 3D visualizations, material selection, and detailed working drawings. It is typically calculated as a percentage of the estimated project cost or as a lump sum based on the scope. For most residential projects, the design fee ranges from **\u20b950,000 to \u20b92,00,000** depending on the size and complexity.\n- **Design fee adjustment:** The design fee is typically adjusted against the total project cost if you proceed with us for execution. In other words, if you hire us for the full project (design + execution), the design fee effectively becomes part of the overall cost rather than an additional charge.\n\nWe charge a design fee because good design takes significant time and expertise. Detailed floor plans, 3D renders, material boards, and working drawings are the foundation of a well-executed project. Studios that offer \"free design\" typically recover that cost through inflated material markups or compromised design quality."
      },
      {
        "question": "What is included in your design fee vs execution cost?",
        "answer": "**Design fee includes:**\n- Site visit and detailed measurements\n- Space planning and layout optimization\n- 2D floor plans and furniture layouts\n- 3D photorealistic renders and walkthroughs for every room\n- Material and finish selection with physical samples\n- Colour scheme and lighting plan\n- Detailed working drawings for carpentry, electrical, plumbing, false ceiling, and tiling\n- Bill of Quantities (BOQ) with itemized costing\n- Two to three rounds of design revisions\n\n**Execution cost includes:**\n- Civil work (if applicable) \u2014 wall modifications, waterproofing, flooring\n- Carpentry \u2014 modular kitchen, wardrobes, TV units, shoe racks, storage units, all built and installed\n- Electrical work \u2014 new points, switches, wiring modifications, light fixture installation\n- Plumbing work \u2014 relocation of points, fixture installation\n- False ceiling \u2014 gypsum or POP, with lighting integration\n- Painting \u2014 walls, ceilings, wood polish or PU finish\n- Hardware \u2014 hinges, channels, drawer systems (Hettich, Hafele, or equivalent)\n- Tile laying and grouting (tiles procured separately or through us)\n- Installation and site cleanup\n- Project management and quality oversight throughout\n\n**Typically quoted separately:**\n- Loose furniture (sofas, dining tables, beds, chairs) \u2014 we can source these for you or you can purchase independently\n- Curtains, blinds, and soft furnishings\n- Appliances (chimney, hob, microwave, washing machine, etc.)\n- Decor items, artwork, and accessories\n- Major civil/structural work beyond standard modifications\n\nEverything is itemized in the BOQ before you approve, so there are no hidden costs."
      },
      {
        "question": "How do payment milestones work?",
        "answer": "We follow a milestone-based payment structure that ensures you only pay as work progresses. This protects both sides \u2014 you don't pay for work that hasn't been done, and we can manage procurement and labour costs smoothly.\n\nHere's the typical structure for a residential project:\n\n1. **Design fee** \u2014 Paid upfront when you sign the design agreement. This kicks off the design phase.\n2. **40% of execution cost** \u2014 Paid upon design approval and before site work begins. This covers material procurement, workshop manufacturing (kitchen cabinets, wardrobes), and initial site mobilization.\n3. **30% of execution cost** \u2014 Paid at the midpoint of execution, typically when carpentry installation begins on site and civil/electrical work is substantially complete.\n4. **20% of execution cost** \u2014 Paid when carpentry installation is complete and painting/finishing work begins.\n5. **10% of execution cost** \u2014 Paid upon final handover after walkthrough and snag list clearance.\n\nThe exact percentages may vary slightly depending on the project size and scope, but the principle remains the same: payments are tied to visible progress milestones.\n\nWe also provide regular progress updates \u2014 including site photos and a milestone tracker \u2014 so you always know where your project stands and what the next payment will cover."
      }
    ]
  },
  {
    "category": "SERVICES",
    "items": [
      {
        "question": "Do you only do interiors or also architecture?",
        "answer": "We do both. beMore Design Studio is a full-service architecture and interior design practice.\n\n**Our architectural services include:**\n- Residential architecture \u2014 new house design from foundation to finish, floor plan design, elevation design, structural planning\n- Renovation architecture \u2014 adding floors, restructuring existing homes, facade upgrades\n- Commercial architecture \u2014 office buildings, retail spaces, restaurant layouts\n\n**Our interior design services include:**\n- Complete home interiors \u2014 space planning, modular kitchens, wardrobes, false ceilings, lighting, furniture, and finishes\n- Hospitality interiors \u2014 caf\u00e9s, restaurants, boutique hotels\n- Commercial interiors \u2014 offices, co-working spaces, retail showrooms\n- Styling and decor \u2014 material selection, colour schemes, accessorizing\n\nMany of our projects involve both \u2014 for example, an independent house where we design the architecture from scratch and then do the complete interiors. Having one studio handle both ensures continuity \u2014 the interior design doesn't fight the architecture, and the architecture is designed with the interior experience in mind from day one.\n\nBoth our founders are registered with the Council of Architecture (COA), bringing professional rigour to both architectural and interior design work."
      },
      {
        "question": "Can you work with my existing furniture?",
        "answer": "Absolutely. Not every project needs to start from zero.\n\nWe regularly work with clients who want to retain specific furniture pieces \u2014 whether it's a family heirloom dining table, a comfortable sofa that's still in great condition, or a wardrobe that was custom-built just a few years ago.\n\nHere's how we approach it:\n\n- **Assessment:** During our site visit, we evaluate your existing furniture for condition, style, and fit with the new design direction.\n- **Integration:** Pieces that are structurally sound and aesthetically compatible are incorporated into the new design. We might suggest re-upholstering a sofa, re-polishing a wooden table, or changing hardware on existing wardrobes to give them a fresh look without replacing them entirely.\n- **Honest recommendation:** If a piece doesn't work with the new layout or is in poor condition, we'll tell you. But we'll never push you to replace something just to increase the project scope.\n\nWorking with existing furniture can also help manage your budget \u2014 especially for items like sofas, dining sets, and beds where good quality pieces last for many years. We'd rather you invest your budget in things that make the biggest impact, like the kitchen, storage, and lighting."
      },
      {
        "question": "Do you provide modular kitchens or custom carpentry?",
        "answer": "We provide both, and often a combination of the two within the same project. This is core to our approach \u2014 we don't believe in a one-size-fits-all solution.\n\n**Modular kitchen elements we use:**\n- Factory-manufactured cabinets with precision edge-banding\n- Hardware systems from Hettich, Hafele, or Ebco (soft-close hinges, tandem box drawers, corner carousels, tall unit pull-outs)\n- Standard module sizes for efficiency and cost control\n\n**Custom carpentry we do:**\n- Bespoke wardrobes designed around your specific clothing, saree, and accessory storage needs\n- Custom TV units, study desks, pooja units, and shoe racks designed to fit exact wall dimensions\n- Built-in storage solutions for awkward spaces \u2014 under staircases, above lofts, around beams and columns\n- Vanity units, display shelves, and bar counters\n\nThe kitchen specifically benefits from a hybrid approach: modular carcasses (for precision and durability) combined with custom panels and countertops (for the exact look and fit you want). This gives you factory-level quality with the customization of carpenter-made furniture.\n\nAll our carpentry uses quality materials \u2014 BWR-grade plywood for wet areas (kitchen, bathroom), commercial plywood for dry areas (bedrooms, living room), with finish options ranging from laminate and veneer to PU, acrylic, and lacquer."
      },
      {
        "question": "What brands and materials do you use?",
        "answer": "We work with trusted brands that balance quality, durability, and value. Here are some of our regular partners:\n\n**Hardware:**\n- Hettich \u2014 soft-close hinges, drawer systems, lift-up mechanisms\n- Hafele \u2014 kitchen accessories, tall unit fittings, smart hardware\n- Ebco \u2014 functional fittings, sliding systems\n\n**Surfaces & Laminates:**\n- Merino Laminates \u2014 wide range of finishes and textures\n- Century Laminates \u2014 durable, cost-effective options\n- Rehau \u2014 PVC edge banding for clean, moisture-resistant edges\n\n**Paints:**\n- Asian Paints \u2014 our primary paint partner for walls, ceilings, and wood finishes\n- We also work with Berger and Nerolac for specific textures and specialty finishes\n\n**Glass & Glazing:**\n- Saint-Gobain \u2014 for glass partitions, shower enclosures, and profile doors\n\n**Countertops & Stone:**\n- Locally sourced granite (Kadappa, Sadarahalli, Rajasthan marble, and other Indian stones)\n- Quartz surfaces for kitchen countertops\n- We source natural stone from Karnataka and Rajasthan quarries where possible\n\n**Plywood & Core Materials:**\n- Century Ply and Greenply BWR-grade for wet areas\n- Commercial-grade plywood for dry areas\n- HDHMR boards where appropriate for specific applications\n\nWe're not locked into any single brand \u2014 material selection is always based on what's right for the specific application, budget, and design intent. For every project, we present physical material samples so you can see and touch the finishes before approving them."
      },
      {
        "question": "Do you handle electrical, plumbing, and painting?",
        "answer": "Yes, we handle everything. beMore provides end-to-end execution, which means you don't need to hire or manage separate contractors for different trades. Our scope covers:\n\n**Electrical:**\n- New switch and socket point placement optimized for your furniture layout\n- Wiring modifications and upgrades\n- Light fixture selection and installation\n- Concealed wiring for a clean finish\n- Geyser, AC, and appliance points\n\n**Plumbing:**\n- Relocation of plumbing points for kitchen or bathroom layout changes\n- New bathroom fitting installation (taps, showers, commodes, basins)\n- Kitchen sink and dishwasher plumbing\n- Water purifier point setup\n\n**And also:**\n- Civil work \u2014 wall breaking, building, waterproofing, tile laying\n- False ceiling \u2014 gypsum, POP, or wood, with integrated lighting\n- Carpentry \u2014 kitchen, wardrobes, TV units, storage, and all custom woodwork\n- Fabrication \u2014 mild steel or SS railings, gates, frames\n- Tiling \u2014 floor and wall tiling in kitchens, bathrooms, balconies\n- Final cleaning and handover\n\nHaving one team manage all trades means better coordination, fewer delays, and consistent quality. You deal with one project manager, not six different contractors."
      },
      {
        "question": "Can you design just one room or does it have to be the full home?",
        "answer": "We take on both full-home projects and single-room projects, though the majority of our work is full-home or multi-room interiors.\n\n**Single-room projects we commonly do:**\n- Kitchen redesign (this is our most common single-room project \u2014 many Bangalore homeowners start with the kitchen and do the rest of the home later)\n- Master bedroom and wardrobe design\n- Living room redesign with TV unit, false ceiling, and accent walls\n- Home office / study room setup\n- Bathroom renovation\n\n**A few things to know about single-room projects:**\n- The per-square-foot cost for a single room is typically slightly higher than a full-home project because fixed costs (site mobilization, project management, transport) are distributed across a smaller scope.\n- Design fees for single-room projects are adjusted proportionally.\n- If you plan to do the rest of the home later, we can design the single room with the full home in mind \u2014 maintaining consistency in materials, colour palette, and style so that future phases feel seamless.\n\nOur honest recommendation: if your budget allows, doing the full home at once is more cost-effective and gives a more cohesive result. But if the kitchen is urgent and the bedrooms can wait six months, we're happy to phase the work to match your finances."
      }
    ]
  },
  {
    "category": "LOCATIONS",
    "items": [
      {
        "question": "Which areas in Bangalore do you serve?",
        "answer": "We serve all of Bangalore \u2014 both within the city and in the rapidly growing suburbs. Our studio is based in Basaveshwar Nagar (near Rajajinagar), and we regularly work across:\n\n**Central & South Bangalore:**\nIndiranagar, Koramangala, HSR Layout, Jayanagar, JP Nagar, Banashankari, Basavanagudi, BTM Layout, Bellandur, Marathahalli\n\n**East & Southeast Bangalore:**\nWhitefield, Sarjapur Road, Electronic City, Bommanahalli, Varthur, Harlur, Kadugodi\n\n**North & Northwest Bangalore:**\nHebbal, Yelahanka, Devanahalli, Thanisandra, RT Nagar, Malleshwaram, Rajajinagar, Sadashivanagar\n\n**West Bangalore:**\nVijayanagar, Nagarbhavi, Kengeri, Mysore Road corridor\n\nWe also work in areas surrounding Bangalore \u2014 Kanakapura Road, Sarjapur, Anekal, and Hosur Road \u2014 where many villa communities and gated developments are located.\n\nFor projects in specific apartment complexes, we're already familiar with the layouts and association rules of most major buildings across these areas \u2014 Brigade, Prestige, Sobha, Godrej, Puravankara, Salarpuria, and others. This local experience helps us design and execute more efficiently."
      },
      {
        "question": "Do you take on projects outside Bangalore?",
        "answer": "Yes, we selectively take on projects outside Bangalore.\n\nWe've worked on projects in other Karnataka cities and are open to projects across South India and beyond, provided the scope and scale justify the travel and coordination involved.\n\n**How out-of-station projects work:**\n- The design phase is handled remotely \u2014 we can work from detailed measurements, floor plans, and video walkthroughs of your space. Video calls and digital collaboration tools make the design process smooth regardless of location.\n- For execution, we either partner with trusted local contractors and vendors in your city (whom we vet and oversee) or deploy our own team for larger projects where it makes sense logistically.\n- Site visits are scheduled at key milestones \u2014 start of work, midpoint review, and final handover at minimum.\n\n**Projects we're most suited for outside Bangalore:**\n- Villa and independent house interiors or architecture (larger scope justifies travel)\n- Hospitality projects \u2014 caf\u00e9, restaurant, or boutique hotel design\n- Commercial and corporate interiors\n- Clients who want a specific design sensibility that they haven't found locally\n\nFor small apartment interiors in cities far from Bangalore, it may make more practical and financial sense to work with a good local designer. We're always honest about this and happy to advise."
      },
      {
        "question": "Do you do site visits before starting?",
        "answer": "Yes, absolutely. A site visit is the very first step of every project and it's non-negotiable for us.\n\nHere's why it matters:\n\n- **Measurements:** We take precise measurements of every room, including ceiling height, beam positions, column locations, window sizes, and door clearances. Floor plans from builders are often inaccurate by several inches, which is enough to throw off a kitchen layout or wardrobe design.\n- **Structural assessment:** We check for existing plumbing risers, electrical panels, gas pipeline routes, drainage slopes, and load-bearing walls. These are constraints that determine what's possible and what isn't in your specific space.\n- **Natural light and ventilation:** We assess how light enters each room at different times of day, which directly influences our material and colour choices. A north-facing bedroom in Bangalore needs a very different approach than a west-facing one.\n- **Existing conditions:** For renovation projects, we check the condition of existing flooring, walls, waterproofing, and fixtures to determine what can be retained and what needs replacement.\n- **Context:** Seeing the building, the neighbourhood, the views from your windows, and the overall vibe of the space gives us design insights that floor plans alone never can.\n\nFor the first consultation, the site visit is part of the free meeting \u2014 you don't pay anything for us to come see your space. For projects outside Bangalore, we arrange site visits at the start and key milestones, or use detailed video walkthroughs and measurements for the initial assessment."
      }
    ]
  }
];
